{
  "stats": {
    "submitted": 50,
    "finished": 50,
    "running": 0
  },
  "data": [
    [
      1,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.396766,
      1707159485.4024148,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      1,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.4199915,
      1707159485.4251912,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      2,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.4283705,
      1707159485.433957,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      2,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.4374652,
      1707159485.442087,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      1,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159485.4452775,
      1707159485.4508474,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      3,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.4552262,
      1707159485.4598334,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      3,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.4624069,
      1707159485.4668148,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      3,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159485.4702966,
      1707159485.4753106,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      4,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.4779043,
      1707159485.4804995,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      4,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.4821885,
      1707159485.4860973,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      4,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159485.4886425,
      1707159485.491348,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      5,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.4936638,
      1707159485.4966323,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      5,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.498464,
      1707159485.502205,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      5,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159485.5045657,
      1707159485.5076568,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      6,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.7255785,
      1707159485.7283258,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      6,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.7311957,
      1707159485.7359152,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      6,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159485.7394507,
      1707159485.7426596,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      7,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.745319,
      1707159485.7478926,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      7,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.7501616,
      1707159485.7530916,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      7,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159485.7554054,
      1707159485.7586796,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      8,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.7615142,
      1707159485.764131,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      8,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.7664406,
      1707159485.769327,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      8,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159485.7716146,
      1707159485.7749333,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      9,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.778881,
      1707159485.7838433,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      9,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.7881618,
      1707159485.793475,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      9,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159485.797497,
      1707159485.8029752,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      10,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.8082993,
      1707159485.8119452,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      10,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.8144283,
      1707159485.819517,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      10,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159485.8252697,
      1707159485.8300006,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      11,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.8333275,
      1707159485.836955,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      11,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.839732,
      1707159485.8426585,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      11,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159485.8449924,
      1707159485.8479338,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      12,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.85164,
      1707159485.8547437,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      12,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.8570833,
      1707159485.8597558,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      12,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159485.8625298,
      1707159485.865312,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      13,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159485.86976,
      1707159485.8727467,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      13,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159485.8754945,
      1707159485.8781645,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      13,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159485.880314,
      1707159485.8833578,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      14,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159486.174176,
      1707159486.179688,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      14,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159486.1848269,
      1707159486.1903489,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      14,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159486.1950881,
      1707159486.2000363,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      15,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159486.207476,
      1707159486.2124987,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      15,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159486.2156825,
      1707159486.2191613,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      15,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159486.2225847,
      1707159486.226589,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      16,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159486.2315629,
      1707159486.2378993,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      16,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159486.2416012,
      1707159486.2450273,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      16,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159486.248376,
      1707159486.2517521,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      17,
      null,
      209652396,
      null,
      Infinity,
      0.0,
      2,
      1707159486.255418,
      1707159486.2973359,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      17,
      null,
      398764591,
      null,
      Infinity,
      0.0,
      2,
      1707159486.301573,
      1707159486.3053262,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ],
    [
      17,
      null,
      924231285,
      null,
      Infinity,
      0.0,
      2,
      1707159486.3085482,
      1707159486.3117044,
      {
        "traceback": "Traceback (most recent call last):\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 184, in run\n    rval = self(config_copy, target_function, kwargs)\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/smac/runner/target_function_runner.py\", line 257, in __call__\n    return algorithm(config, **algorithm_kwargs)\n  File \"/home/gonzalo/Documentos/TFM/LunaLanderPPO/SMAC/2_svm_cv.py\", line 58, in train\n    if \"gamma\" in config:\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 151, in __contains__\n    return item in self\n  [Previous line repeated 987 more times]\n  File \"/home/gonzalo/.local/lib/python3.8/site-packages/ConfigSpace/configuration.py\", line 148, in __contains__\n    if not isinstance(item, str):\nRecursionError: maximum recursion depth exceeded while calling a Python object\n",
        "error": "RecursionError('maximum recursion depth exceeded while calling a Python object')"
      }
    ]
  ],
  "configs": {
    "1": {
      "C": 0.03992740880515713,
      "kernel": "rbf",
      "shrinking": true,
      "gamma": "auto"
    },
    "2": {
      "C": 1.2760639488343621,
      "kernel": "linear",
      "shrinking": false
    },
    "3": {
      "C": 99.73882304607206,
      "kernel": "sigmoid",
      "shrinking": true,
      "coef0": 4.547900483012199,
      "gamma": "value",
      "gamma_value": 0.4125654333467708
    },
    "4": {
      "C": 0.0032115258048034567,
      "kernel": "poly",
      "shrinking": false,
      "coef0": 7.344286264851689,
      "degree": 3,
      "gamma": "auto"
    },
    "5": {
      "C": 0.0066006851689440205,
      "kernel": "sigmoid",
      "shrinking": false,
      "coef0": 6.1642263643443584,
      "gamma": "auto"
    },
    "6": {
      "C": 224.2012371372442,
      "kernel": "linear",
      "shrinking": false
    },
    "7": {
      "C": 19.549524484259873,
      "kernel": "poly",
      "shrinking": false,
      "coef0": 6.399210213275238,
      "degree": 3,
      "gamma": "auto"
    },
    "8": {
      "C": 7.505241622349544,
      "kernel": "sigmoid",
      "shrinking": false,
      "coef0": 4.146619399905235,
      "gamma": "value",
      "gamma_value": 0.00031647170716777857
    },
    "9": {
      "C": 4.135997393839888,
      "kernel": "sigmoid",
      "shrinking": false,
      "coef0": 1.433532874090464,
      "gamma": "value",
      "gamma_value": 0.06247784993545861
    },
    "10": {
      "C": 1.96282248134428,
      "kernel": "sigmoid",
      "shrinking": true,
      "coef0": 1.1827442586893322,
      "gamma": "auto"
    },
    "11": {
      "C": 1.8590843630169627,
      "kernel": "rbf",
      "shrinking": false,
      "gamma": "auto"
    },
    "12": {
      "C": 0.4222048983149828,
      "kernel": "linear",
      "shrinking": true
    },
    "13": {
      "C": 0.348280208702833,
      "kernel": "rbf",
      "shrinking": false,
      "gamma": "value",
      "gamma_value": 7.015940040157503
    },
    "14": {
      "C": 8.291821660947624,
      "kernel": "linear",
      "shrinking": false
    },
    "15": {
      "C": 0.004594633206288104,
      "kernel": "linear",
      "shrinking": true
    },
    "16": {
      "C": 0.6278626332563011,
      "kernel": "sigmoid",
      "shrinking": false,
      "coef0": 0.6414749634878436,
      "gamma": "value",
      "gamma_value": 0.07995301861119038
    },
    "17": {
      "C": 0.008991196763419824,
      "kernel": "sigmoid",
      "shrinking": true,
      "coef0": 5.666014542065751,
      "gamma": "value",
      "gamma_value": 0.0012410501153697251
    }
  },
  "config_origins": {
    "1": "Initial Design: Sobol",
    "2": "Initial Design: Sobol",
    "3": "Initial Design: Sobol",
    "4": "Initial Design: Sobol",
    "5": "Initial Design: Sobol",
    "6": "Acquisition Function Maximizer: Random Search (sorted)",
    "7": "Acquisition Function Maximizer: Random Search (sorted)",
    "8": "Acquisition Function Maximizer: Random Search (sorted)",
    "9": "Acquisition Function Maximizer: Random Search (sorted)",
    "10": "Acquisition Function Maximizer: Random Search (sorted)",
    "11": "Acquisition Function Maximizer: Random Search (sorted)",
    "12": "Acquisition Function Maximizer: Random Search (sorted)",
    "13": "Acquisition Function Maximizer: Random Search (sorted)",
    "14": "Acquisition Function Maximizer: Random Search (sorted)",
    "15": "Acquisition Function Maximizer: Random Search (sorted)",
    "16": "Acquisition Function Maximizer: Random Search (sorted)",
    "17": "Acquisition Function Maximizer: Random Search (sorted)"
  }
}